---
- name: Copy ssh config
  copy:
    src: files/git.config
    dest: "/home/{{user}}/.ssh/config"
    owner: "{{user}}"
    group: "{{user}}"

- name: Create directory structure if they don't exist
  file:
    path: "/home/{{user}}/projects/{{ item.path }}"
    state: directory
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775
  with_items: "{{ git_projects }}"

- name: Clone git projects.
  git:
    repo: "{{ item.git }}"
    dest: "/home/{{user}}/projects/{{ item.path }}"
    accept_hostkey: true
    force: yes
  with_items: "{{ git_projects }}"
