---
- name: Install packages
  include_tasks: install_package.yml
  with_flattened:
    - "{{ dev_packages }}"

- name: Update all packages
  apt: upgrade=yes

- name: Update vm options in IntelliJ Idea
  include_tasks: idea64_vmoptions.yml

