---
- name: Install packages
  include_tasks: install_package.yml
  with_flattened:
    - "{{ system_packages }}"

- name: Update all packages
  apt: upgrade=yes

- name: "Copy inputrc for {{user}}"
  copy:
    src: inputrc
    dest: "/home/{{user}}/.inputrc"
    owner: "{{user}}"
    group: "{{user}}"

- name: Set environment via bashrc
  lineinfile:
    dest: "/home/{{user}}/.bashrc"
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ bashrc_env }}"