---
commands:

  # set Regional-Format
  - update-locale LANG=en_US.UTF-8
  - update-locale LC_NUMERIC=de_DE.UTF-8
  - update-locale LC_TIME=de_DE.UTF-8
  - update-locale LC_MONETARY=de_DE.UTF-8
  - update-locale LC_PAPER=de_DE.UTF-8
  - update-locale LC_NAME=de_DE.UTF-8
  - update-locale LC_ADDRESS=de_DE.UTF-8
  - update-locale LC_TELEPHONE=de_DE.UTF-8
  - update-locale LC_MEASUREMENT=de_DE.UTF-8
  - update-locale LC_IDENTIFICATION=de_DE.UTF-8
  - update-locale LANGUAGE=en_US
    
    # Installing VisualVM installs also other versions of Java. So we need to set a default java version.
    # To see all current java installed, run: sudo update-java-alternatives -l
  - update-java-alternatives -s /usr/lib/jvm/java-1.8.0-openjdk-amd64
    
    # Correct time-zone, see https://vitux.com/how-to-change-the-timezone-on-your-ubuntu-system/
  - unlink /etc/localtime
  - ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
    
    # bug with Google Chrome, it creates 2 same files:
    # /etc/apt/sources.list.d/google-chrome.list and
    # /etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list
    # Only a single file must be left
  - rm -rf /etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list